version: "3"

tasks:
  update-osx:
    desc: Update osx system
    cmds:
      - NIXPKGS_ALLOW_UNFREE=1 nix run nix-darwin -- switch --flake . --impure

  update-pkgs:
    desc: Update upstream
    cmds:
      - nix flake update
