version: "3"

tasks:
  update-osx:
    desc: Update OSX system
    cmds:
      - nix run nix-darwin -- switch --flake .

  update-osx-impure:
    desc: Update OSX system
    cmds:
      - NIXPKGS_ALLOW_UNFREE=1 nix run nix-darwin -- switch --flake . --impure

  update-pkgs:
    desc: Update upstream
    cmds:
      - nix flake update

  gc:
    desc: Remove pkgs older than 7 days
    cmds:
      - nix-collect-garbage --delete-older-than 7d
