
"$schema" = 'https://starship.rs/config-schema.json'

# Just in case
#    

format = """
[](sapphire)\
$os\
$directory\
${custom.is_not_git}\
${custom.is_git}\
$git_branch\
$git_status\
$fill\
[](fg:base2)\
[ ](fg:subtext0 bg:base2)\
$cmd_duration\
[](bg:peach fg:base2)\
$docker_context\
[](fg:peach bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:mauve)\
$kubernetes\
[](fg:mauve bg:base2)\
$time\
[ ](fg:base2)\
$line_break$character"""

palette = 'catppuccin_macchiato'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
sapphire1 = "#517690"
sapphire0 = "#304256"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base2 = "#404566"
base1 = "#353954"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
style = "bg:sapphire fg:surface0"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[fill]
symbol = "—"
style = "surface0"

[cmd_duration]
min_time = 500
format = '[ took](bg:base2 fg:subtext0)[ $duration ](bg:base2 bold yellow)'

[battery]
full_symbol        = "🔋 "
charging_symbol    = "⚡️ "
discharging_symbol = "💀 "

[username]
show_always = true
style_user = "bg:base1 fg:subtext1"
style_root = "bg:base1 fg:subtext1"
format = '[ $user ]($style)'

[directory]
style = "fg:crust bg:sapphire"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[custom.is_git]
symbol = ""
style = "fg:sapphire bg:base2"
format = '[$symbol]($style)' 
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["zsh", "--no-rcs"]

[custom.is_not_git]
symbol = ""
style = "fg:sapphire bg:base"
format = '[$symbol]($style)' 
when = "test ! $(git rev-parse --is-inside-work-tree 2> /dev/null)"
shell = ["zsh", "--no-rcs"]

[git_branch]
symbol = ""
style = "fg:subtext0 bg:base2"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:base2"
format = '[($all_status$ahead_behind) ]($style)[](fg:base2 bg:base)'
untracked = '[ ](bg:base2 text)'
staged = '[ ](bg:base2 green)'
modified = '[ ](bg:base2 yellow)'
ahead = '[ ⇡${count}](bg:base2 green)'
diverged = '[  ⇡${ahead_count}⇣${behind_count}](bg:base2 text)'
behind = '[ ⇣${count}]'
deleted = '[ ](bg:base2 red)'
stashed = ''
renamed = ''

[nodejs]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:base bg:teal"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:base bg:peach"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:subtext1 bg:base2"
format = '[ $time]($style)'

[line_break]
disabled = false 

[kubernetes]
symbol = "󰠳 "
format = "[ $symbol$context ]($style)"
style = "fg:base bg:mauve"
disabled = false

[character]
disabled = false
success_symbol = '[ ✤ ](bold fg:mauve)'
error_symbol = '[ ✤ ](bold fg:red)'
vimcmd_symbol = '[  ](bold fg:sky)'
vimcmd_replace_one_symbol = '[ ](bold fg:lavender)'
vimcmd_replace_symbol = '[ ](bold fg:lavender)'
vimcmd_visual_symbol = '[ ](bold fg:lavender)'
