if [ -n "${ZSH_DEBUGRC+1}" ]; then
    zmodload zsh/zprof
fi
eval $(/opt/homebrew/bin/brew shellenv)

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

plugins=(
	git
	docker
	kubectl
	zsh-autosuggestions
	zsh-completions
	zsh-syntax-highlighting
	)

source $ZSH/oh-my-zsh.sh

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# --------- FZF --------
# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# Configure fd with FZF
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# source ~/work/tools/fzf-git.sh/fzf-git.sh

# load custom data and fns 
[[ -f ~/.config/diaball/apikeys.sh ]] && source ~/.config/diaball/apikeys.sh
[[ -f ~/.config/diaball/fns.sh ]] && source ~/.config/diaball/fns.sh


# ------ Init starship prompt
eval "$(starship init zsh)"
# We are setting title using hooks
DISABLE_AUTO_TITLE="true"

function add_newline_btw_prompts() {
  precmd() {
    echo
  }
}

# autoload -Uz add-zsh-hook
add-zsh-hook precmd set_title_precmd
add-zsh-hook precmd add_newline_btw_prompts
add-zsh-hook preexec set_title_preexec


# Add hook for zellij tab
# zellij_tab_name_updategg
# chpwd_functions+=(zellij_tab_name_update)

eval "$(direnv hook zsh)"
eval "$(zoxide init zsh)"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml"

source <(switcher init zsh)

if [ -n "${ZSH_DEBUGRC+1}" ]; then
    zprof
fi

