{
  config,
  lib,
  pkgs,
  osConfig,
  ...
}:
let
  cfg = config.my.programs.sketchybar;

  # The window manager is chosen on the system side (my.windowManager.backend in
  # darwin/window-manager.nix), so read it from there rather than duplicating it.
  backend = osConfig.my.windowManager.backend;

  # Workspace names come from the AeroSpace module's own persistent-workspaces so
  # the bar and the window manager cannot disagree about what exists.
  workspaces = osConfig.services.aerospace.settings.persistent-workspaces or [ ];

  # Which display each workspace starts on, from the same monitor assignment the
  # window manager uses. Only used for the first paint - space_app.sh re-reads it
  # from AeroSpace on every update, so undocking corrects itself.
  monitorAssignment =
    osConfig.services.aerospace.settings.workspace-to-monitor-force-assignment or { };
  displayFor =
    ws:
    let
      v = monitorAssignment.${ws} or null;
    in
    if builtins.isInt v then toString v else "all";

  # Facts the shell needs, resolved now rather than probed at runtime. common.sh
  # sources this.
  wmFacts = pkgs.writeText "sketchybar-wm.sh" ''
    # Generated by programs/sketchybar.nix - do not edit.
    WM_BACKEND="${backend}"
    WM_WORKSPACES=(${lib.concatStringsSep " " (map lib.escapeShellArg workspaces)})
    WM_WORKSPACE_DISPLAYS=(${
      lib.concatStringsSep " " (map (ws: lib.escapeShellArg (displayFor ws)) workspaces)
    })
  '';

  # The shared tree plus exactly one backend's items and plugins, assembled at
  # build time. Switching my.windowManager.backend produces a different store
  # path, so nothing in the bar has to branch on the backend itself.
  sketchybarConfig = pkgs.runCommand "sketchybar-config-${backend}" { } ''
    cp -R ${../config/sketchybar} $out
    chmod -R u+w $out

    cp -R ${../config/sketchybar-wm + "/${backend}"}/. $out/
    cp ${wmFacts} $out/wm.sh

    # The app icon map ships from the same derivation as the font itself, so the
    # glyph names the plugins emit can never drift out of sync with the glyphs
    # the font actually provides. The font is installed via fonts.packages.
    cp ${pkgs.sketchybar-app-font}/bin/icon_map.sh $out/plugins/icon_map.sh

    chmod -R a-w $out
  '';
in
{
  options.my.programs.sketchybar = {
    enable = lib.mkEnableOption "My sketchybar home configuration";
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."sketchybar" = {
      source = sketchybarConfig;
      recursive = true;
    };
  };
}
